test=Test
welcome=Welcome to Planner!🎉I'm here to help you orginize your tasks and manage your schedule. Feel free to ask me anything or start by adding your first task!
menuButton=Create task, Settings, My tasks
settinsHandler=Select one of the sections below
settinsButton=Edit language
choiceLang=Choose a language
newLang=The language has been changed to English
confirmLang=Confirm language, Confirm
back=Back