test=Test
welcome=Welcome to Planner!🎉I'm here to help you orginize your tasks and manage your schedule. Feel free to ask me anything or start by adding your first task!
menuButton=Create task, Settings, My tasks
settinsHandler=Select one of the sections below
settinsButton=Edit language
choiceLang=Choose a language
newLang=The language has been changed to English
confirmLang=Confirm language, Confirm
move=Go ahead
back=Back
panelCreate = You're in the task creation panel
actionCreate = Enter the title of the task:
descCreate = Enter the description of the task:
dateCreate = Enter the date and time of the task in this format: 2024-12-23 10:23
confirmCreate = Here is your task
startTask = The task is going to start at
addTask = Your task has been added to the database
cancelCreateTask = You've canceled the task
errors_message = The message length is very small, try again_The description length is small, it must be more than 10, try again_The date is wrong, try again
