"""add column expectation

Revision ID: eac96f6f0138
Revises: fc80f963c599
Create Date: 2024-04-22 21:53:49.659879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac96f6f0138'
down_revision: Union[str, None] = 'fc80f963c599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('expectation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'expectation')
    # ### end Alembic commands ###
